[package]
name = "service-diff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.4"
curl = "0.4.46"
log = "0.4"
simple_logger = "4.3.3"
structopt = "0.3.13"
